#!/bin/bash

selected_pod=$(kubectl get pods | tail -n +2 | fzf | awk '{print $1}')

# If a pod was selected, exec into it
if [ -n "$selected_pod" ]; then
  kubectl exec --stdin --tty "$selected_pod" -- /bin/sh
else
  echo "No pod selected."
fi

